language: python
cache: pip
services: postgresql

matrix:
  include:
    - python: 3.8
      dist: xenial
      env: TOX_ENV="py38,lint"

before_install:
  - pip install --upgrade pip

before_script:
  - psql -c "create database test_users_api;" -U postgres

install:
  - pip install tox poetry

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
